#!/usr/bin/python

import os, sys

if len(sys.argv) == 1:
    print "ff grep-expr [dir] [grep-flags]"
    exit();

if len(sys.argv) >= 3:
    loc = sys.argv[2]
else:
    loc = '.'
    
cmd = "find " + loc + " -regex '.*[.]\(cpp\|hpp\|hh\|cc\|C\|H\|c\|h\|f90\|F90\|f\|F\|hy\)' -exec grep "

if len(sys.argv) >= 4:
    cmd += sys.argv[3] + " "
else:
    cmd += '-n' + " "

cmd += '"' + sys.argv[1] + '"' + " \{} \+"

print cmd
os.system(cmd)


# For quote marks:
# pfind.py . '\"Method'
